blog:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: blog
    username: root
    password:

jwt:
  tokenHeader: Authorization
  secret: 'nb666nb666nb666nb666nb666nb666nb666'
  expiration: 604800000
  tokenHead: 'Bearer '

security:
  ignored:
    urls:
      - /user/login
      - /user/save
      - /category/**
      - /admin/login
      - /admin/logout
      - /admin/save
      - /test/**
